# GitLab CI/CD pipeline for Cashnest
stages:
  - deploy

before_script:
  - apt-get update && apt-get install -y openssh-client

deploy_backend:
  stage: deploy
  only:
    - main
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > id_rsa
    - chmod 600 id_rsa
    - ssh -o StrictHostKeyChecking=no -i id_rsa $EC2_USER@$EC2_HOST '
      cd ~/cashnest &&
      git pull origin main &&
      cd server &&
      docker-compose down &&
      docker-compose up -d --build
      '
    - rm -f id_rsa
  when: manual

deploy_frontend:
  stage: deploy
  only:
    - main
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > id_rsa
    - chmod 600 id_rsa
    - ssh -o StrictHostKeyChecking=no -i id_rsa $EC2_USER@$EC2_HOST '
      cd ~/cashnest &&
      git pull origin main &&
      cd client &&
      docker-compose down &&
      docker-compose up -d --build
      '
    - rm -f id_rsa
  when: manual

debug_ssh:
  stage: deploy
  script:
    - echo "✅ EC2_USER: $EC2_USER"
    - echo "✅ EC2_HOST: $EC2_HOST"
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - echo "✅ SSH_PRIVATE_KEY loaded with $(wc -l < id_rsa) lines"
    - rm id_rsa
  when: manual
