# GitLab CI/CD pipeline for Fintrackr
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose

build_backend:
  stage: build
  script:
    - cd server
    - docker build -t fintrackr-backend .
  artifacts:
    paths:
      - server

deploy_backend:
  stage: deploy
  script:
    - echo "Deploy backend to EC2 or registry here"
  when: manual

build_frontend:
  stage: build
  script:
    - cd client
    - docker build -t fintrackr-frontend .
  artifacts:
    paths:
      - client

deploy_frontend:
  stage: deploy
  script:
    - echo "Deploy frontend to EC2 or registry here"
  when: manual
