version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    restart: unless-stopped
  frontend:
    build: ./client
    ports:
      - "8080:80"
    restart: unless-stopped
