name: Semgrep
on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
