name: Semgrep

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [main, master]
    # Run when rules or JS/TS code changes
    paths:
      - .semgrep.yml
      - .github/workflows/semgrep.yml
      - "**/*.js"
      - "**/*.ts"
  # Daily scheduled scan (UTC time)
  schedule:
    - cron: "40 04 * * *"

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep:1.131.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
