name: Semgrep
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
