name: Semgrep

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to EC2?"
        required: true
        default: "false"
  pull_request: {}
  push:
    branches:
      - main
      - master
  schedule:
    # random HH:MM to avoid load spikes at midnight
    - cron: "40 4 * * *"

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKE }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci

  deploy:
    name: Deploy to EC2 / aka check apt-get
    needs: semgrep
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true'
    steps:
      - name: Install SSH client on runner
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Prepare SSH key
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run simple check on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo apt-get update && sudo apt-get install -y openssh-client"
